name: Build ZMK firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install west
          west init -l config
          west update
          west zephyr-export

      - name: Build
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD=cck_ball_left
